# Generated by Django 3.2 on 2023-08-26 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20230824_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='empresa',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='ofertas'),
        ),
    ]
