# Generated by Django 3.2 on 2023-08-25 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='experiencia_cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='oferta',
            name='experiencia_detalle',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='fecha_cierre',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='fecha_registro',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='puesto',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='responsabilidades',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='salario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
